=encoding utf8

=head1 NAME

Blog - Blog articles on http://fseitz.de/blog

=head1 DESCRIPTION

Die Quellen der Artikel, die ich auf meinem Blog L<http://fseitz.de/blog>
veröffentlicht habe.

=over 2

=item *

L<Enscript: Quelltext von der Kommandozeile aus drucken|http://fseitz.de/blog/index.php?/archives/122-x.html>

=item *

L<Globale in-place Textersetzung mit sed oder Perl|http://fseitz.de/blog/index.php?/archives/121-x.html>

=item *

L<Oracle+Linux: ORA-00845: MEMORY_TARGET not supported on this system|http://fseitz.de/blog/index.php?/archives/62-x.html>

=item *

L<Globale Verbreitung von DNS-Änderungen überprüfen|http://fseitz.de/blog/index.php?/archives/116-x.html>

=item *

L<Perl: Hostname zu IP-Adresse ermitteln|http://fseitz.de/blog/index.php?/archives/114-x.html>

=item *

L<Perl: Speedy (CGI-SpeedyCGI) unter Perl 5.10 und höher kompilieren|http://fseitz.de/blog/index.php?/archives/113-x.html>

=item *

L<Helligkeit von Farben des RGB-Farbraums berechnen|http://fseitz.de/blog/index.php?/archives/112-x.html>

=item *

L<Apache: Bessere access.log-Datei definieren|http://fseitz.de/blog/index.php?/archives/117-x.html>

=item *

L<Overlays in Google Earth einbinden|http://fseitz.de/blog/index.php?/archives/25-x.html>

=item *

L<Apache: Aufsetzen einer CGI Webapplikation|http://fseitz.de/blog/index.php?/archives/115-x.html>

=item *

L<Apache: Redirection auf Subdirectory|http://fseitz.de/blog/index.php?/archives/27-x.html>

=item *

L<PostgreSQL: Installation und Konfiguration|http://fseitz.de/blog/index.php?/archives/6-x.html>

=item *

L<Perl: Text im richtigen Character Encoding ausgeben|http://fseitz.de/blog/index.php?/archives/84-x.html>

=item *

L<LaTeX: Briefe mit scrlttr2 ohne Einrückung setzen|http://fseitz.de/blog/index.php?/archives/110-x.html>

=item *

L<Debian Testing (stretch) mit Xfce Desktop|http://fseitz.de/blog/index.php?/archives/108-x.html>

=item *

L<Unix Epoch in lesbare Zeitangabe wandeln und umgekehrt|http://fseitz.de/blog/index.php?/archives/105-x.html>

=item *

L<fslint: Datei-Dubletten finden|http://fseitz.de/blog/index.php?/archives/111-x.html>

=item *

L<Audacity: YouTube-Sperre verhindern|http://fseitz.de/blog/index.php?/archives/59-x.html>

=item *

L<Dateibaum chronologisch sortiert anzeigen|http://fseitz.de/blog/index.php?/archives/104-x.html>

=item *

L<Operationen auf Bildern|http://fseitz.de/blog/index.php?/archives/107-x.html>

=item *

L<libav/ffmpeg: Video-Seitenverhältnis ändern|http://fseitz.de/blog/index.php?/archives/109-x.html>

=item *

L<Minecraft-Server unter Linux einrichten|http://fseitz.de/blog/index.php?/archives/106-x.html>

=item *

L<Bilder / Grafiken in HTML einbetten|http://fseitz.de/blog/index.php?/archives/103-x.html>

=item *

L<Leeres lokales SVN-Repository anlegen|http://fseitz.de/blog/index.php?/archives/102-x.html>

=item *

L<Linux Kernelparameter ändern|http://fseitz.de/blog/index.php?/archives/101-x.html>

=item *

L<Perl: Web Services mit SOAP::WSDL ansprechen|http://fseitz.de/blog/index.php?/archives/118-x.html>

=item *

L<Eclipse: EPIC-Plugin für Perl installieren|http://fseitz.de/blog/index.php?/archives/120-x.html>

=item *

L<JavaScript: Existenz eines Bildes prüfen|http://fseitz.de/blog/index.php?/archives/119-x.html>

=item *

L<Unicode: UTF-8 validieren|http://fseitz.de/blog/index.php?/archives/99-x.html>

=item *

L<SSH: Über SSH-Tunnel mit MySQL Datenbank verbinden|http://fseitz.de/blog/index.php?/archives/97-x.html>

=item *

L<Perl: Module installieren mit cpanm|http://fseitz.de/blog/index.php?/archives/96-x.html>

=item *

L<Perl: Testsuite auf Basis des Test Anything Protocol (TAP)|http://fseitz.de/blog/index.php?/archives/95-x.html>

=item *

L<Shell: stderr auf Pipe umleiten und andere dup-Operationen|http://fseitz.de/blog/index.php?/archives/94-x.html>

=item *

L<CSS: Erstes Kind- bzw. Folgeelement gestalten|http://fseitz.de/blog/index.php?/archives/93-x.html>

=item *

L<meld: Unterschiede zwischen Dateien anzeigen und bearbeiten|http://fseitz.de/blog/index.php?/archives/92-x.html>

=item *

L<ffmpeg: Verfügbare Filter anzeigen|http://fseitz.de/blog/index.php?/archives/91-x.html>

=item *

L<ffmpeg: Video deinterlacen|http://fseitz.de/blog/index.php?/archives/90-x.html>

=item *

L<Film mit kdenlive/MLT in Teilen rendern|http://fseitz.de/blog/index.php?/archives/89-x.html>

=item *

L<Wechseldatenträger mit Ext[234]-Dateisystem ein Label geben|http://fseitz.de/blog/index.php?/archives/88-x.html>

=item *

L<Liste der geöffneten TCP-Ports|http://fseitz.de/blog/index.php?/archives/87-x.html>

=item *

L<Streamripper: Internet-Radio aufzeichnen|http://fseitz.de/blog/index.php?/archives/86-x.html>

=item *

L<Lookup-Trigger für Oracle und PostgreSQL|http://fseitz.de/blog/index.php?/archives/85-x.html>

=item *

L<PostgreSQL: Notizen zum psql Kommando-Interpreter|http://fseitz.de/blog/index.php?/archives/81-x.html>

=item *

L<Android: Entwicklungsumgebung unter Linux aufsetzen|http://fseitz.de/blog/index.php?/archives/78-x.html>

=item *

L<Java SE 7 JDK unter Linux installieren|http://fseitz.de/blog/index.php?/archives/79-x.html>

=item *

L<Notizen zu Amazons eBook-Reader Kindle 4|http://fseitz.de/blog/index.php?/archives/77-x.html>

=item *

L<Debian GNU/Linux von USB-Stick booten|http://fseitz.de/blog/index.php?/archives/76-x.html>

=item *

L<HTTPS-Server: SSL-Zertifikat erwerben und einrichten|http://fseitz.de/blog/index.php?/archives/74-x.html>

=item *

L<STRATO HiDrive unter Linux nutzen|http://fseitz.de/blog/index.php?/archives/75-x.html>

=item *

L<Nexus S i9023 mit unvollständigem Android Release von Amazon|http://fseitz.de/blog/index.php?/archives/71-x.html>

=item *

L<Cisco VPN-Verbindung (vpnclient) loggen/debuggen|http://fseitz.de/blog/index.php?/archives/55-x.html>

=item *

L<Cisco vpnclient unter Linux Kernel 2.6.38+|http://fseitz.de/blog/index.php?/archives/56-x.html>

=item *

L<Perl: Klassische Formularprogrammierung|http://fseitz.de/blog/index.php?/archives/67-x.html>

=item *

L<SQL: Dubletten finden|http://fseitz.de/blog/index.php?/archives/66-x.html>

=item *

L<MySQL: Data Directory neu aufsetzen|http://fseitz.de/blog/index.php?/archives/65-x.html>

=item *

L<MySQL: Mehrere Instanzen auf einem Server|http://fseitz.de/blog/index.php?/archives/64-x.html>

=item *

L<Linksammlung: UTF-8 Portierung|http://fseitz.de/blog/index.php?/archives/63-x.html>

=item *

L<SVN: Auf Branch entwickeln|http://fseitz.de/blog/index.php?/archives/60-x.html>

=item *

L<ffmpeg: Lautstärke anheben oder verringern|http://fseitz.de/blog/index.php?/archives/58-x.html>

=item *

L<Linksammlung Video und Audio|http://fseitz.de/blog/index.php?/archives/57-x.html>

=item *

L<Oracle 11g unter Linux installieren|http://fseitz.de/blog/index.php?/archives/54-x.html>

=item *

L<mod_perl: Eigenen Perl-Interpreter für Virtual Host|http://fseitz.de/blog/index.php?/archives/53-x.html>

=item *

L<Finde Dateinamen mit Sonderzeichen|http://fseitz.de/blog/index.php?/archives/52-x.html>

=item *

L<Seamonkey installieren (Unix)|http://fseitz.de/blog/index.php?/archives/51-x.html>

=item *

L<FONIC: Klingelzeit verlängern, Kontostand abfragen etc.|http://fseitz.de/blog/index.php?/archives/72-x.html>

=item *

L<scp: Whitespace in Remote-Dateinamen|http://fseitz.de/blog/index.php?/archives/48-x.html>

=item *

L<DVD-Chapter rippen|http://fseitz.de/blog/index.php?/archives/70-x.html>

=item *

L<MySQL: Bessere Antwortzeiten durch bessere Query-Pläne|http://fseitz.de/blog/index.php?/archives/47-x.html>

=item *

L<MySQL: Remote-Zugriff einrichten|http://fseitz.de/blog/index.php?/archives/46-x.html>

=item *

L<FFmpeg Operationen|http://fseitz.de/blog/index.php?/archives/68-x.html>

=item *

L<Cookies per JavaScript setzen|http://fseitz.de/blog/index.php?/archives/45-x.html>

=item *

L<ROWNUM unter MySQL|http://fseitz.de/blog/index.php?/archives/44-x.html>

=item *

L<Javascript: HTML-Formular abbrechen|http://fseitz.de/blog/index.php?/archives/43-x.html>

=item *

L<Perl: Apache2::Reload installieren|http://fseitz.de/blog/index.php?/archives/42-x.html>

=item *

L<CSS: Listen portabel einrücken|http://fseitz.de/blog/index.php?/archives/41-x.html>

=item *

L<HTML-Konstrukte mit CSS gestalten|http://fseitz.de/blog/index.php?/archives/40-x.html>

=item *

L<dvgrab: Video von miniDV-Camcorder lesen|http://fseitz.de/blog/index.php?/archives/61-x.html>

=item *

L<Perl: POD als Programm-Hilfetext|http://fseitz.de/blog/index.php?/archives/39-x.html>

=item *

L<Medion Life S60003 MP3 Player unter Debian|http://fseitz.de/blog/index.php?/archives/38-x.html>

=item *

L<Perl: Plus / Minus Unendlich|http://fseitz.de/blog/index.php?/archives/37-x.html>

=item *

L<Perl: Dirhandles objektorientiert|http://fseitz.de/blog/index.php?/archives/35-x.html>

=item *

L<Perl: Filehandles objektorientiert|http://fseitz.de/blog/index.php?/archives/34-x.html>

=item *

L<Perl: Crash bei Umleitung von STDERR auf Skalare Variable|http://fseitz.de/blog/index.php?/archives/33-x.html>

=item *

L<GNU Makefile zum Konvertieren von Dateien|http://fseitz.de/blog/index.php?/archives/31-x.html>

=item *

L<Syntax-Highlighting mit highlight|http://fseitz.de/blog/index.php?/archives/30-x.html>

=item *

L<Syntax-Highlighting mit perltidy|http://fseitz.de/blog/index.php?/archives/29-x.html>

=item *

L<Perl: Effizient Zeichen zählen|http://fseitz.de/blog/index.php?/archives/28-x.html>

=item *

L<Rsync: Abweichende Rechte einstellen|http://fseitz.de/blog/index.php?/archives/26-x.html>

=item *

L<Email-Adressen in HTML vor Spammern schützen|http://fseitz.de/blog/index.php?/archives/23-x.html>

=item *

L<Perl: Gleitkomma-Zahlen ausgeben wie sie sind|http://fseitz.de/blog/index.php?/archives/24-x.html>

=item *

L<HTML: String in Entity-Schreibweise wandeln|http://fseitz.de/blog/index.php?/archives/22-x.html>

=item *

L<SSH: Timeout unterbinden|http://fseitz.de/blog/index.php?/archives/21-x.html>

=item *

L<SSH: Automatisch einloggen|http://fseitz.de/blog/index.php?/archives/20-x.html>

=item *

L<PostgreSQL: TIMESTAMP nach EPOCH wandeln und zurück|http://fseitz.de/blog/index.php?/archives/19-x.html>

=item *

L<Verzeichnisse via rsync abgleichen|http://fseitz.de/blog/index.php?/archives/18-x.html>

=item *

L<Perl: Operationen auf Symlinks|http://fseitz.de/blog/index.php?/archives/17-x.html>

=item *

L<Liste der zusätzlich installierten Perl-Module|http://fseitz.de/blog/index.php?/archives/16-x.html>

=item *

L<Iconsammlungen|http://fseitz.de/blog/index.php?/archives/14-x.html>

=item *

L<Unicode: ISO-8859-1 nach UTF-8 konvertieren|http://fseitz.de/blog/index.php?/archives/12-x.html>

=item *

L<Speicherbedarf von Perl-Variablen|http://fseitz.de/blog/index.php?/archives/11-x.html>

=item *

L<CSS: Text-Eingabefelder gestalten|http://fseitz.de/blog/index.php?/archives/10-x.html>

=item *

L<CSS: Table Cellspacing unterdrücken|http://fseitz.de/blog/index.php?/archives/8-x.html>

=item *

L<CSS: Dreispaltiges Seitenlayout|http://fseitz.de/blog/index.php?/archives/7-x.html>

=item *

L<Validierung von HTML- und CSS-Code|http://fseitz.de/blog/index.php?/archives/9-x.html>

=item *

L<Änderungen an Serendipity|http://fseitz.de/blog/index.php?/archives/15-x.html>

=item *

L<Style der Serendipity Admin-Oberfläche ändern|http://fseitz.de/blog/index.php?/archives/4-x.html>

=item *

L<Perl-Interpreter über Shebang-Zeile suchen|http://fseitz.de/blog/index.php?/archives/1-x.html>

=item *

L<Installation von Serendipity|http://fseitz.de/blog/index.php?/archives/2-x.html>

=item *

L<Haftungsausschluss|http://fseitz.de/blog/index.php?/archives/80-x.html>

=item *

L<Eröffnung des Blog|http://fseitz.de/blog/index.php?/archives/3-x.html>

=back

=head1 DOWNLOAD

$ git clone https://github.com/s31tz/Blog.git

=head1 AUTHOR

Frank Seitz, L<http://fseitz.de>

=head1 COPYRIGHT

Copyright © 2010-2015 Frank Seitz
