=encoding utf8

=head1 NAME

Blog - Blog articles

=head1 DESCRIPTION

Die Quellen der Artikel, die ich auf meinem Blog L<http://fseitz.de/blog>
veröffentlicht habe.

=over 2

=item *

L<Grep: Finde in Dateibaum Worte eines bestimmten Musters|https://github.com/s31tz/Blog/blob/master/article/119-Finde-in-Dateibaum-Worte-eines-bestimmten-Musters.sdoc>

=item *

L<Perl: Modulpfade ermitteln|https://github.com/s31tz/Blog/blob/master/article/118-Perl-Modulpfade-ausgeben.sdoc>

=item *

L<Perl: Erreichbarkeit eines Host prüfen|https://github.com/s31tz/Blog/blob/master/article/116-Perl-Erreichbarkeit-Host-pruefen.sdoc>

=item *

L<Entfernung zwischen zwei Punkten auf der Erdoberfläche berechnen|https://github.com/s31tz/Blog/blob/master/article/115-Entfernung-auf-Erdoberflaeche-berechnen.sdoc>

=item *

L<HTTP: Datei-Download mit Namensvorschlag|https://github.com/s31tz/Blog/blob/master/article/114-HTTP-Datei-Download-mit-Namensvorschlag.sdoc>

=item *

L<Bildschirmkoordinaten von XY-Plots berechnen|https://github.com/s31tz/Blog/blob/master/article/113-XY-Plot-Bildschirmkoordinaten-berechnen.sdoc>

=item *

L<Perl: UTF-8 und ISO-8859-1 Dateien erkennen und automatisch dekodieren|https://github.com/s31tz/Blog/blob/master/article/112-Perl-UTF-8-und-ISO-8859-1-Dateien-automatisch-dekodieren.sdoc>

=item *

L<GnuPG: Verschlüsseln, entschlüsseln und andere Operationen|https://github.com/s31tz/Blog/blob/master/article/111-GnuPG-Datei-verschluesseln.sdoc>

=item *

L<Enscript: Quelltext von der Kommandozeile aus drucken|https://github.com/s31tz/Blog/blob/master/article/110-Enscript-Quelltext-von-der-Kommandozeile-aus-drucken.sdoc>

=item *

L<Globale in-place Textersetzung mit sed oder Perl|https://github.com/s31tz/Blog/blob/master/article/109-Globale-Textersetzung.sdoc>

=item *

L<Oracle+Linux: ORA-00845: MEMORY_TARGET not supported on this system|https://github.com/s31tz/Blog/blob/master/article/108-Oracle+Linux-ORA-00845-MEMORY-TARGET-not-supported-on-this-system.sdoc>

=item *

L<Globale Verbreitung von DNS-Änderungen überprüfen|https://github.com/s31tz/Blog/blob/master/article/107-Globale-Verbreitung-von-DNS-Aenderungen-ueberpruefen.sdoc>

=item *

L<Perl: Hostname zu IP-Adresse ermitteln|https://github.com/s31tz/Blog/blob/master/article/106-Perl-Hostname-zu-IP-Adresse-ermitteln.sdoc>

=item *

L<Perl: Speedy (CGI-SpeedyCGI) unter Perl 5.10 und höher kompilieren|https://github.com/s31tz/Blog/blob/master/article/105-Perl-Speedy-CGI-SpeedyCGI-unter-Perl-5.10-und-hoeher-kompilieren.sdoc>

=item *

L<Helligkeit von Farben des RGB-Farbraums berechnen|https://github.com/s31tz/Blog/blob/master/article/104-Helligkeit-von-Farben-des-RGB-Farbraums-berechnen.sdoc>

=item *

L<Apache: Bessere access.log-Datei definieren|https://github.com/s31tz/Blog/blob/master/article/103-Apache-Bessere-access.log-Datei-definieren.sdoc>

=item *

L<Overlays in Google Earth einbinden|https://github.com/s31tz/Blog/blob/master/article/102-Overlays-in-Google-Earth-einbinden.sdoc>

=item *

L<Apache: Aufsetzen einer CGI Webapplikation|https://github.com/s31tz/Blog/blob/master/article/101-Apache-Eine-CGI-Webapplikation-aufsetzen.sdoc>

=item *

L<Apache: Redirection auf Subdirectory|https://github.com/s31tz/Blog/blob/master/article/100-Apache-Redirection-auf-Subdirectory.sdoc>

=item *

L<PostgreSQL: Installation und Konfiguration|https://github.com/s31tz/Blog/blob/master/article/099-PostgreSQL-Installation-und-Konfiguration.sdoc>

=item *

L<Perl: Text im richtigen Character Encoding ausgeben|https://github.com/s31tz/Blog/blob/master/article/098-Perl-Text-im-richtigen-Character-Encoding-ausgeben.sdoc>

=item *

L<LaTeX: Briefe mit scrlttr2 ohne Einrückung setzen|https://github.com/s31tz/Blog/blob/master/article/097-LaTeX-Briefe-mit-scrlttr2-ohne-Einrueckung-setzen.sdoc>

=item *

L<Debian Testing (stretch) mit Xfce Desktop|https://github.com/s31tz/Blog/blob/master/article/096-Debian-Testing-stretch-mit-Xfce-Desktop.sdoc>

=item *

L<Unix Epoch in lesbare Zeitangabe wandeln und umgekehrt|https://github.com/s31tz/Blog/blob/master/article/095-Unix-Epoch-in-lesbare-Zeitangabe-wandeln-und-umgekehrt.sdoc>

=item *

L<fslint: Datei-Dubletten finden|https://github.com/s31tz/Blog/blob/master/article/094-fslint-Datei-Dubletten-finden.sdoc>

=item *

L<Audacity: YouTube-Sperre verhindern|https://github.com/s31tz/Blog/blob/master/article/093-Audacity-YouTube-Sperre-verhindern.sdoc>

=item *

L<Dateibaum chronologisch sortiert anzeigen|https://github.com/s31tz/Blog/blob/master/article/092-Dateibaum-chronologisch-sortiert-anzeigen.sdoc>

=item *

L<Operationen auf Bildern|https://github.com/s31tz/Blog/blob/master/article/091-Operationen-auf-Bildern.sdoc>

=item *

L<libav/ffmpeg: Video-Seitenverhältnis ändern|https://github.com/s31tz/Blog/blob/master/article/090-libav-ffmpeg-Video-Seitenverhaeltnis-aendern.sdoc>

=item *

L<Minecraft-Server unter Linux einrichten|https://github.com/s31tz/Blog/blob/master/article/089-Minecraft-Server-unter-Linux-einrichten.sdoc>

=item *

L<Bilder / Grafiken in HTML einbetten|https://github.com/s31tz/Blog/blob/master/article/088-Bilder-Grafiken-in-HTML-einbetten.sdoc>

=item *

L<Leeres lokales SVN-Repository anlegen|https://github.com/s31tz/Blog/blob/master/article/087-Leeres-lokales-SVN-Repository-anlegen.sdoc>

=item *

L<Linux Kernelparameter ändern|https://github.com/s31tz/Blog/blob/master/article/086-Linux-Kernelparameter-aendern.sdoc>

=item *

L<Perl: Web Services mit SOAP::WSDL ansprechen|https://github.com/s31tz/Blog/blob/master/article/085-Perl-Web-Services-mit-SOAP-WSDL-ansprechen.sdoc>

=item *

L<Eclipse: EPIC-Plugin für Perl installieren|https://github.com/s31tz/Blog/blob/master/article/084-Eclipse-EPIC-Plugin-fuer-Perl-installieren.sdoc>

=item *

L<JavaScript: Existenz eines Bildes prüfen|https://github.com/s31tz/Blog/blob/master/article/083-JavaScript-Existenz-eines-Bildes-pruefen.sdoc>

=item *

L<Unicode: UTF-8 validieren|https://github.com/s31tz/Blog/blob/master/article/082-Unicode-UTF-8-validieren.sdoc>

=item *

L<SSH: Über SSH-Tunnel mit MySQL Datenbank verbinden|https://github.com/s31tz/Blog/blob/master/article/081-SSH-Ueber-SSH-Tunnel-mit-MySQL-Datenbank-verbinden.sdoc>

=item *

L<Perl: Module installieren mit cpanm|https://github.com/s31tz/Blog/blob/master/article/080-Perl-Module-installieren-mit-cpanm.sdoc>

=item *

L<Perl: Testsuite auf Basis des Test Anything Protocol (TAP)|https://github.com/s31tz/Blog/blob/master/article/079-Perl-Testsuite-auf-Basis-des-Test-Anything-Protocol-TAP.sdoc>

=item *

L<Shell: stderr auf Pipe umleiten und andere dup-Operationen|https://github.com/s31tz/Blog/blob/master/article/078-Shell-stderr-auf-Pipe-umleiten-und-andere-dup-Operationen.sdoc>

=item *

L<CSS: Erstes Kind- bzw. Folgeelement gestalten|https://github.com/s31tz/Blog/blob/master/article/077-CSS-Erstes-Kind-bzw.-Folgeelement-gestalten.sdoc>

=item *

L<meld: Unterschiede zwischen Dateien anzeigen und bearbeiten|https://github.com/s31tz/Blog/blob/master/article/076-meld-Unterschiede-zwischen-Dateien-anzeigen-und-bearbeiten.sdoc>

=item *

L<ffmpeg: Verfügbare Filter anzeigen|https://github.com/s31tz/Blog/blob/master/article/075-ffmpeg-Verfuegbare-Filter-anzeigen.sdoc>

=item *

L<ffmpeg: Video deinterlacen|https://github.com/s31tz/Blog/blob/master/article/074-ffmpeg-Video-deinterlacen.sdoc>

=item *

L<Film mit kdenlive/MLT in Teilen rendern|https://github.com/s31tz/Blog/blob/master/article/073-Film-mit-kdenlive-MLT-in-Teilen-rendern.sdoc>

=item *

L<Wechseldatenträger mit Ext[234]-Dateisystem ein Label geben|https://github.com/s31tz/Blog/blob/master/article/072-Wechseldatentraeger-mit-Ext-234-Dateisystem-ein-Label-geben.sdoc>

=item *

L<Liste der geöffneten TCP-Ports|https://github.com/s31tz/Blog/blob/master/article/071-Liste-der-geoeffneten-TCP-Ports.sdoc>

=item *

L<Streamripper: Internet-Radio aufzeichnen|https://github.com/s31tz/Blog/blob/master/article/070-Streamripper-Internet-Radio-aufzeichnen.sdoc>

=item *

L<Lookup-Trigger für Oracle und PostgreSQL|https://github.com/s31tz/Blog/blob/master/article/069-Lookup-Trigger-fuer-Oracle-und-PostgreSQL.sdoc>

=item *

L<PostgreSQL: Notizen zum psql Kommando-Interpreter|https://github.com/s31tz/Blog/blob/master/article/068-PostgreSQL-Notizen-zum-psql-Kommando-Interpreter.sdoc>

=item *

L<Android: Entwicklungsumgebung unter Linux aufsetzen|https://github.com/s31tz/Blog/blob/master/article/067-Android-Entwicklungsumgebung-unter-Linux-aufsetzen.sdoc>

=item *

L<Java SE 7 JDK unter Linux installieren|https://github.com/s31tz/Blog/blob/master/article/066-Java-SE-7-JDK-unter-Linux-installieren.sdoc>

=item *

L<Notizen zu Amazons eBook-Reader Kindle 4|https://github.com/s31tz/Blog/blob/master/article/065-Notizen-zu-Amazons-eBook-Reader-Kindle-4.sdoc>

=item *

L<Debian GNU/Linux von USB-Stick booten|https://github.com/s31tz/Blog/blob/master/article/064-Debian-GNU-Linux-von-USB-Stick-booten.sdoc>

=item *

L<HTTPS-Server: SSL-Zertifikat erwerben und einrichten|https://github.com/s31tz/Blog/blob/master/article/063-HTTPS-Server-SSL-Zertifikat-erwerben-und-einrichten.sdoc>

=item *

L<STRATO HiDrive unter Linux nutzen|https://github.com/s31tz/Blog/blob/master/article/062-STRATO-HiDrive-unter-Linux-nutzen.sdoc>

=item *

L<Nexus S i9023 mit unvollständigem Android Release von Amazon|https://github.com/s31tz/Blog/blob/master/article/061-Nexus-S-i9023-mit-unvollstaendigem-Android-Release-von-Amazon.sdoc>

=item *

L<Cisco VPN-Verbindung (vpnclient) loggen/debuggen|https://github.com/s31tz/Blog/blob/master/article/060-Cisco-VPN-Verbindung-vpnclient-loggen-debuggen.sdoc>

=item *

L<Cisco vpnclient unter Linux Kernel 2.6.38+|https://github.com/s31tz/Blog/blob/master/article/059-Cisco-vpnclient-unter-Linux-Kernel-2.6.38+.sdoc>

=item *

L<Perl: Klassische Formularprogrammierung|https://github.com/s31tz/Blog/blob/master/article/058-Perl-Klassische-Formularprogrammierung.sdoc>

=item *

L<SQL: Dubletten finden|https://github.com/s31tz/Blog/blob/master/article/057-SQL-Doubletten-finden.sdoc>

=item *

L<MySQL: Data Directory neu aufsetzen|https://github.com/s31tz/Blog/blob/master/article/056-MySQL-Data-Directory-neu-aufsetzen.sdoc>

=item *

L<MySQL: Mehrere Instanzen auf einem Server|https://github.com/s31tz/Blog/blob/master/article/055-MySQL-Mehrere-Instanzen-auf-einem-Server.sdoc>

=item *

L<Linksammlung: UTF-8 Portierung|https://github.com/s31tz/Blog/blob/master/article/054-Linksammlung-UTF-8-Portierung.sdoc>

=item *

L<SVN: Auf Branch entwickeln|https://github.com/s31tz/Blog/blob/master/article/053-SVN-Auf-Branch-entwickeln.sdoc>

=item *

L<ffmpeg: Lautstärke anheben oder verringern|https://github.com/s31tz/Blog/blob/master/article/052-ffmpeg-Lautstaerke-anheben-oder-verringern.sdoc>

=item *

L<Linksammlung Video und Audio|https://github.com/s31tz/Blog/blob/master/article/051-Linksammlung-Video-und-Audio.sdoc>

=item *

L<Oracle 11g unter Linux installieren|https://github.com/s31tz/Blog/blob/master/article/050-Oracle-11g-unter-Linux-installieren.sdoc>

=item *

L<mod_perl: Eigenen Perl-Interpreter für Virtual Host|https://github.com/s31tz/Blog/blob/master/article/049-mod-perl-Eigenen-Perl-Interpreter-fuer-Virtual-Host.sdoc>

=item *

L<Finde Dateinamen mit Sonderzeichen|https://github.com/s31tz/Blog/blob/master/article/048-Finde-Dateinamen-mit-Sonderzeichen.sdoc>

=item *

L<Seamonkey installieren (Unix)|https://github.com/s31tz/Blog/blob/master/article/047-Seamonkey-installieren-Unix.sdoc>

=item *

L<FONIC: Klingelzeit verlängern, Kontostand abfragen etc.|https://github.com/s31tz/Blog/blob/master/article/046-FONIC-Klingelzeit-verlaengern-Kontostand-abfragen-etc..sdoc>

=item *

L<scp: Whitespace in Remote-Dateinamen|https://github.com/s31tz/Blog/blob/master/article/045-scp-Whitespace-in-Remote-Dateinamen.sdoc>

=item *

L<DVD-Chapter rippen|https://github.com/s31tz/Blog/blob/master/article/044-DVD-Chapter-rippen.sdoc>

=item *

L<MySQL: Bessere Antwortzeiten durch bessere Query-Pläne|https://github.com/s31tz/Blog/blob/master/article/043-MySQL-Bessere-Antwortzeiten-durch-bessere-Query-Plaene.sdoc>

=item *

L<MySQL: Remote-Zugriff einrichten|https://github.com/s31tz/Blog/blob/master/article/042-MySQL-Remote-Zugriff-einrichten.sdoc>

=item *

L<FFmpeg Operationen|https://github.com/s31tz/Blog/blob/master/article/041-FFmpeg-Operationen.sdoc>

=item *

L<Cookies per JavaScript setzen|https://github.com/s31tz/Blog/blob/master/article/040-Cookies-per-JavaScript-setzen.sdoc>

=item *

L<ROWNUM unter MySQL|https://github.com/s31tz/Blog/blob/master/article/039-ROWNUM-unter-MySQL.sdoc>

=item *

L<Javascript: HTML-Formular abbrechen|https://github.com/s31tz/Blog/blob/master/article/038-Javascript-HTML-Formular-abbrechen.sdoc>

=item *

L<Perl: Apache2::Reload installieren|https://github.com/s31tz/Blog/blob/master/article/037-Perl-Apache2-Reload-installieren.sdoc>

=item *

L<CSS: Listen portabel einrücken|https://github.com/s31tz/Blog/blob/master/article/036-CSS-Listen-portabel-einruecken.sdoc>

=item *

L<HTML-Konstrukte mit CSS gestalten|https://github.com/s31tz/Blog/blob/master/article/035-HTML-Konstrukte-mit-CSS-gestalten.sdoc>

=item *

L<dvgrab: Video von miniDV-Camcorder lesen|https://github.com/s31tz/Blog/blob/master/article/034-dvgrab-Video-von-miniDV-Camcorder-lesen.sdoc>

=item *

L<Perl: POD als Programm-Hilfetext|https://github.com/s31tz/Blog/blob/master/article/033-Perl-POD-als-Programm-Hilfetext.sdoc>

=item *

L<Medion Life S60003 MP3 Player unter Debian|https://github.com/s31tz/Blog/blob/master/article/032-Medion-Life-S60003-MP3-Player-unter-Debian.sdoc>

=item *

L<Perl: Plus / Minus Unendlich|https://github.com/s31tz/Blog/blob/master/article/031-Perl-Plus-Minus-Unendlich.sdoc>

=item *

L<Perl: Dirhandles objektorientiert|https://github.com/s31tz/Blog/blob/master/article/030-Perl-Dirhandles-objektorientiert.sdoc>

=item *

L<Perl: Filehandles objektorientiert|https://github.com/s31tz/Blog/blob/master/article/029-Perl-Filehandles-objektorientiert.sdoc>

=item *

L<Perl: Crash bei Umleitung von STDERR auf Skalare Variable|https://github.com/s31tz/Blog/blob/master/article/028-Perl-Crash-bei-Umleitung-von-STDERR-auf-Skalare-Variable.sdoc>

=item *

L<GNU Makefile zum Konvertieren von Dateien|https://github.com/s31tz/Blog/blob/master/article/027-GNU-Makefile-zum-Konvertieren-von-Dateien.sdoc>

=item *

L<Syntax-Highlighting mit highlight|https://github.com/s31tz/Blog/blob/master/article/026-Syntax-Highlighting-mit-highlight.sdoc>

=item *

L<Syntax-Highlighting mit perltidy|https://github.com/s31tz/Blog/blob/master/article/025-Syntax-Highlighting-mit-perltidy.sdoc>

=item *

L<Perl: Effizient Zeichen zählen|https://github.com/s31tz/Blog/blob/master/article/024-Perl-Effizient-Zeichen-zaehlen.sdoc>

=item *

L<Rsync: Abweichende Rechte einstellen|https://github.com/s31tz/Blog/blob/master/article/023-Rsync-Abweichende-Rechte-einstellen.sdoc>

=item *

L<Email-Adressen in HTML vor Spammern schützen|https://github.com/s31tz/Blog/blob/master/article/022-Email-Adressen-in-HTML-vor-Spammern-schuetzen.sdoc>

=item *

L<Perl: Gleitkomma-Zahlen ausgeben wie sie sind|https://github.com/s31tz/Blog/blob/master/article/021-Perl-Gleitkomma-Zahlen-ausgeben-wie-sie-sind.sdoc>

=item *

L<HTML: String in Entity-Schreibweise wandeln|https://github.com/s31tz/Blog/blob/master/article/020-HTML-String-in-Entity-Schreibweise-wandeln.sdoc>

=item *

L<SSH: Timeout unterbinden|https://github.com/s31tz/Blog/blob/master/article/019-SSH-Timeout-unterbinden.sdoc>

=item *

L<SSH: Automatisch einloggen|https://github.com/s31tz/Blog/blob/master/article/018-SSH-Automatisch-einloggen.sdoc>

=item *

L<PostgreSQL: TIMESTAMP nach EPOCH wandeln und zurück|https://github.com/s31tz/Blog/blob/master/article/017-PostgreSQL-TIMESTAMP-nach-EPOCH-wandeln-und-zurueck.sdoc>

=item *

L<Verzeichnisse via rsync abgleichen|https://github.com/s31tz/Blog/blob/master/article/016-Verzeichnisse-via-rsync-abgleichen.sdoc>

=item *

L<Perl: Operationen auf Symlinks|https://github.com/s31tz/Blog/blob/master/article/015-Perl-Operationen-auf-Symlinks.sdoc>

=item *

L<Liste der zusätzlich installierten Perl-Module|https://github.com/s31tz/Blog/blob/master/article/014-Liste-der-zusaetzlich-installierten-Perl-Module.sdoc>

=item *

L<Iconsammlungen|https://github.com/s31tz/Blog/blob/master/article/013-Iconsammlungen.sdoc>

=item *

L<Unicode: ISO-8859-1 nach UTF-8 konvertieren|https://github.com/s31tz/Blog/blob/master/article/012-Unicode-ISO-8859-1-nach-UTF-8-konvertieren.sdoc>

=item *

L<Speicherbedarf von Perl-Variablen|https://github.com/s31tz/Blog/blob/master/article/011-Speicherbedarf-von-Perl-Variablen.sdoc>

=item *

L<CSS: Text-Eingabefelder gestalten|https://github.com/s31tz/Blog/blob/master/article/010-CSS-Text-Eingabefelder-gestalten.sdoc>

=item *

L<CSS: Table Cellspacing unterdrücken|https://github.com/s31tz/Blog/blob/master/article/009-CSS-Table-Cellspacing-unterdruecken.sdoc>

=item *

L<CSS: Dreispaltiges Seitenlayout|https://github.com/s31tz/Blog/blob/master/article/008-CSS-Dreispaltiges-Seitenlayout.sdoc>

=item *

L<Validierung von HTML- und CSS-Code|https://github.com/s31tz/Blog/blob/master/article/007-Validierung-von-HTML-und-CSS-Code.sdoc>

=item *

L<Änderungen an Serendipity|https://github.com/s31tz/Blog/blob/master/article/006-Aenderungen-an-Serendipity.sdoc>

=item *

L<Style der Serendipity Admin-Oberfläche ändern|https://github.com/s31tz/Blog/blob/master/article/005-Style-der-Serendipity-Admin-Oberflaeche-aendern.sdoc>

=item *

L<Perl-Interpreter über Shebang-Zeile suchen|https://github.com/s31tz/Blog/blob/master/article/004-Perl-Interpreter-ueber-Shebang-Zeile-suchen.sdoc>

=item *

L<Installation von Serendipity|https://github.com/s31tz/Blog/blob/master/article/003-Installation-von-Serendipity.sdoc>

=item *

L<Haftungsausschluss|https://github.com/s31tz/Blog/blob/master/article/002-Haftungsausschluss.sdoc>

=item *

L<Eröffnung des Blog|https://github.com/s31tz/Blog/blob/master/article/001-Eroeffnung-des-Blog.sdoc>

=back

=head1 AUTHOR

Frank Seitz, L<http://fseitz.de>

=head1 COPYRIGHT

Copyright (C) 2010-2015 Frank Seitz
