#!/usr/bin/env perl

use strict;
use warnings;

unless (@ARGV) {
    $0 =~ s|.*/||;
    die "Usage: $0 STRING\n";
}

my $str = shift;
# begin
while ($str =~ /(.)/g) {
    printf '&#%d;',ord $1;
}
# end

# eof
