package Blog::Base::DirHandle;
use base qw/Blog::Base::Object/;

# Generated by CoTeDo - DO NOT EDIT!

use strict;
use warnings;
use utf8;

# -----------------------------------------------------------------------------

=encoding utf8

=head1 NAME

Blog::Base::DirHandle - Verzeichnis-Handle

=head1 BASE CLASS

L<Blog::Base::Object>

=head1 SYNOPSIS

    use Blog::Base::DirHandle;
    
    my $dh = Blog::Base::DirHandle->new($dir);
    while (my $entry = $dh->next) {
        say $entry;
    }
    $dh->close;

=head1 DESCRIPTION

Die Klasse stellt eine objektorientierte Schnittstelle zu
Perls Directory Handles her. Mit den Methoden der Klasse kann
ein Verzeichnis geöffnet und über seine Einträge iteriert werden.

=head1 METHODS

=head2 Konstruktor/Destruktor

=head3 new() - Instanziiere Directory-Handle

=head4 Synopsis

    $dh = $class->new($dir);

=head4 Description

Instanziiere ein Dirhandle-Objekt für Verzeichnis $dir und liefere
eine Referenz auf dieses Objekt zurück.

=cut

# -----------------------------------------------------------------------------

sub new {
    my ($class,$dir) = @_;

    opendir my $dh,$dir or do {
        $class->throw(
            q{DIR-00001: Verzeichnis öffnen fehlgeschlagen},
            Dir=>$dir,
            Error=>"$!",
        );
    };

    return bless $dh,$class;
}

# -----------------------------------------------------------------------------

=head3 close() - Schließe Verzeichnis

=head4 Synopsis

    $dh->close;

=head4 Description

Schließe das Verzeichnis. Die Methode liefert keinen Wert zurück.

=cut

# -----------------------------------------------------------------------------

sub close {
    my ($self) = @_;

    closedir $self or do {
        $self->throw(
            q{DIR-00002: Dirhandle schließen fehlgeschlagen},
            Error=>"$!",
        );
    };

    $_[0] = undef;

    return;
}

# -----------------------------------------------------------------------------

=head2 Operationen

=head3 next() - Liefere nächsten Verzeichniseintrag

=head4 Synopsis

    $entry = $dh->next;

=head4 Description

Liefere den nächsten Verzeichniseintrag. Die Einträge werden in
der Reihenfolge geliefert, wie sie im Verzeichnis stehen, also
de facto ungeordnet. Ist das Ende erreicht, liefere undef.

=cut

# -----------------------------------------------------------------------------

sub next {
    return readdir shift;
}

# -----------------------------------------------------------------------------

=head1 AUTHOR

Frank Seitz, L<http://fseitz.de/>

=head1 COPYRIGHT

Copyright (C) 2010-2015 Frank Seitz

=cut

# -----------------------------------------------------------------------------

1;

# eof
